<a href="https://colab.research.google.com/github/jannat0718/Tensorflow-Tutorial/blob/main/Zero_to_mastery_tensor_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix
matrix=tf.constant([[10,7,5],
                    [7,10,6],
                    [3,4,1]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  5],
       [ 7, 10,  6],
       [ 3,  4,  1]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# tf.constant() By deafult create int32, indicate how precisely a data saved into a memory.The less the dtype number ,the less memory it required.
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                   [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

#Creating tensor with tf.variable

In [ ]:
# create scalar tensor
changable_tensor=tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# lets try to change 1 of the element in our changable_tensor
changable_tensor[0]=7
changable_tensor

TypeError: ignored

In [ ]:
# Try .assaign
changable_tensor[0].assign(7)
changable_tensor

In [ ]:
# Letss try to change our element using tf.constant
unchangable_tensor=tf.constant([10,7])
unchangable_tensor

In [ ]:
unchangable_tensor[0].assign(7)#.assign( )function dosent work with tf.contant()
unchangable_tensor

#creating tensor from Numpy arrays

In [ ]:
# tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Turn numpy array into tensor as tensor could run on gpu faster and easily
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
type(A),type(B)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
#Reshape the elements
A=tf.constant(numpy_A,shape=(3,8,1))
A

<tf.Tensor: shape=(3, 8, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]]], dtype=int32)>

# Tensor attributs
1.   shape
2.   rank
3.   dimensions
4.   size


In [ ]:
# Create a rank 4 tensor (4 dimension = rank 4)
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# get various attributes of our tensor
print("Datatype of every elements:", rank_4_tensor.dtype)
print("Number of Dimensions(Rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every elements: <dtype: 'float32'>
Number of Dimensions(Rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


#Indexing tensor & expanding tensor
Tensor can be indexed just like python lists

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
#Getting 1st 2 elements of tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the 1st elements from every dimentions except the last one
rank_4_tensor[:1,:1,:1],rank_4_tensor[:1,:1,:1,:]


(<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
##Create rank 2 tensor
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#last item in a rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add a extra dimension to our rank 2 tensor keeping same elements
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#alternative to tf.axis
tf.expand_dims(rank_2_tensor,axis=-1)#'-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)#'0' means expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)#'01' means expand the middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

#Tensor vector mathmatical operation

In [ ]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

Elementwise operation

In [ ]:
add=tf.add(x,y)
add=x+y
print(add)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
sub=tf.subtract(x,y)
sub=x-y
print(sub)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [ ]:
div=tf.divide(x,y)
div=x/y
print(div)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [ ]:
mul=tf.multiply(x,y)
mul=x*y
print(mul)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


Dot product: elementwise multiple then add all

In [ ]:
dot=tf.tensordot(x,y,axes=1)
print(dot)
manual_dot=tf.reduce_sum(x*y,axis=0)
print(manual_dot)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
#elementwise Power operation/exponentiation
z=x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


#Tensor Matrix operations

In [ ]:
a=tf.random.normal((2,3),dtype=tf.float32)
b=tf.random.normal((3,4),dtype=tf.float32)
a,b

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 1.5482024, -2.4443521,  0.4717021],
        [ 1.3235328, -1.2327696,  1.4298201]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-1.0897679 ,  0.90225387,  0.71811914,  0.2107073 ],
        [-0.7862297 , -0.46823537,  0.89695907,  0.4716944 ],
        [ 0.05223528,  0.41242936,  0.21202193, -0.4944309 ]],
       dtype=float32)>)

In [ ]:
mat_mul=tf.matmul(a,b)### dtype need to be same precision
print(mat_mul)
easy_mat_mul=a@b
print(easy_mat_mul)

tf.Tensor(
[[ 0.25928044  2.7359476  -0.980679   -1.0599937 ]
 [-0.3984164   2.3610888   0.14786357 -1.0095596 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.25928044  2.7359476  -0.980679   -1.0599937 ]
 [-0.3984164   2.3610888   0.14786357 -1.0095596 ]], shape=(2, 4), dtype=float32)


#Indexing vector tensor

In [ ]:
x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices=tf.constant([4,7])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([3 3], shape=(2,), dtype=int32)


#Indexing matrix tensor

In [ ]:
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x)
print('Rank:',x.ndim)
print(x[0,:])
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Rank: 2
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Reshping

In [ ]:
x=tf.range(9)
print(x)
x=tf.reshape(x,(3,3))
print(x)
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


#create a class and call it

In [ ]:
class Person:
  def __init__(self, _name,_age):
    self.name = _name
    self.age=_age
    
   
  def sayHi(self,_location):
    self.location=_location
    print('Hello, my name is ' + self.name +' and I am '+ str(self.age)+ ' years old.'+'I am from '+self.location+'.')
    
p1 = Person('Jannat',33)
p1.sayHi('Dhaka')

Hello, my name is Jannat and I am 33 years old.I am from Dhaka.
